### ISSUE TITLE
beta users subscribe with access code

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/bot#11]
we are going to instruct Beta testers to subscribe with a special access code

work with Vinnie to decide how the command works. Codes will be a hex value up to 7 chars (eg. 317FF9D). The /user API endpoint will accept the access code and confirm if it is valid.

**Comment by Brbb** [comment]
The command `/token <user_token>` provides what we need to send after `/start`the user token as `/user` parameter. 
Eg.: 
```{
chat_id: 12345
token: ABC1234
}```
