### ISSUE TITLE
save ITT team chat_ids for testing/debugging

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/bot#19]
For testing purposes, we will want some ITT team members to have a different experience than the common average user.

In order to do this, we need to have a specific setting for internal test users.

## Proposed Solutions

1. Hard-Coded setting
store chat_ids as an environment variable
When filters select which users to send a signal to, these chat ids will be exceptions to those filtering rules

2. Users settings parameter
Let the backend and DB keep track of which chat_id's (users table) are internal team members. This setting could be added to the /user API so that members could leave/join by a secret settings command or special passcode code

**Comment by Brbb** [comment]
Adoption of a _super token_ for the ITT members
