### ISSUE TITLE
feedback command

### ISSUE THREAD

**Issue by tomcounsell** [IntelligentTrading/bot#8]
##Description

`/feedback <text>` command for users to leave a message that will be sent to our team

## Implementation

see docs for /feedback API endpoint
will require POST request

**Comment by tomcounsell** [comment]
@Brbb this is marked as waiting, should I start?
if it's ready on your end, let me know

**Comment by Brbb** [comment]
I can build it as node service separate from the core api and save feedbacks on a trello board or any other service

**Comment by Brbb** [comment]
For some reason I'm able to publish on my ITT board if I run the service locally but not if I use the heroku endpoint.
